publishDir = "docs"

baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "James Jansson Team for NSW"
  subtitle    = "Candidates for Humans"

  cover       = "img/blog-cover.jpg"
  defaultSocialImg = "img/social.jpg"
  description = "Candidates for Humans."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["custom.css"]
  RSSLink = ""

  twitterName = "jj4nsw"
  fbName = "JamesJanssonTeamForNSW"
  #githubName = "jamesjansson"

  authorisation = "Authorised by Saritha Manickam 49 Harrington st Enmore"

  logo = "img/jj4nsw-button.png"
  whiteHeaderLogo = "img/jj4nsw-title-logo-white.png"
  darkHeaderLogo = "img/jj4nsw-title-logo-black.png"
  orgName = "James Jansson Team for NSW"
  orgWebsite = "https://jj4nsw.org"
  orgDescription = "Candidates for humans"

  author = "James Jansson"
  authorAvatar = "img/jj4nsw-button.png"
  authorLocation = "Sydney, Australia"
  authorWebsite = "https://jj4nsw.org"
  authorDescription = "is part of the James Jansson Team for NSW Legislative Council (state upper house)."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

#[[menu.main]]
#  name = "Home"
#  url = "/"
#  weight = 200

# [[menu.main]]
#   name = "About"
#   url = "/about/"
#   weight = 100

# [[menu.main]]
#   name = "Food"
#   url = "/categories/food/"
#   weight = 99

# [[menu.main]]
#   name = "External"
#   url = "https://google.com/"
#   weight = 95